# DataBase configuration
spring.application.name=login_system

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:140101}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${SV_PORT:8080}

# JWT
jwt.secret-key=${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS0zMmNoYXJz}
jwt.expiration-access=${JWT_EXPIRATION_ACCESS:3600000}
jwt.expiration-refresh=${JWT_EXPIRATION_REFRESH:604800000}

# Frontend
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

# Mail
app.mail.from=no-reply@nebula.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bninamango.personal@gmail.com
spring.mail.password=gngimxpjsukcpzao
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Login
logging.level.org.springframework.security=DEBUG